### ISSUE TITLE
rip backtracks too far back (performance issue)

### ISSUE THREAD

**Issue by notatallshaw** [prefix-dev/rip#174]
**Environment:** Linux Python 3.11

**Command**: `cargo r -- apache-airflow[all]==2.8.1`

**Error**:
```
2024-01-25T20:07:15.642751Z  INFO get_sdist_metadata{name=apache-beam version=2.42.0}: rattler_installs_packages::index::http: executing request url=https://files.pythonhosted.org/packages/c7/c3/55076fc728723ef927521abaa1955213d094933dc36d4a2008d5101e1af5/wheel-0.42.0-py3-none-any.whl#sha256=177f9c9b0d45c47873b619f5b650346d632cdc35fb5e4d25058e09c9e581433d cache_mode=Default
2024-01-25T20:07:16.079011Z ERROR rattler_installs_packages::index::package_database: Error from source distributions 'apache-beam-2.42.0.zip' skipped: 
 could not build wheel: <string>:28: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/tmp/.tmpYAeJQs/build_frontend.py", line 124, in <module>
    get_requires_for_build_wheel(backend, work_dir)
  File "/tmp/.tmpYAeJQs/build_frontend.py", line 58, in get_requires_for_build_wheel
    result = f()
             ^^^
  File "/tmp/.tmpYAeJQs/venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpYAeJQs/venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/tmp/.tmpYAeJQs/venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/.tmpYAeJQs/venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 99, in <module>
  File "/tmp/.tmpYAeJQs/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 528, in get_distribution
    dist = get_provider(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpYAeJQs/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 400, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpYAeJQs/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpYAeJQs/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpYAeJQs/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip' distribution was not found and is required by the application

thread 'main' panicked at 'assertion failed: self.decision_tracker.assigned_value(solvable_id) == Some(true)', /home/damian/.cargo/git/checkouts/resolvo-09a21884be70392c/7c1fa14/src/solver/mod.rs:219:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected Behavior**:  The issue isn't the error itself, this package is too old to install for my environment. 

Rather there is some performance characteristic that feels wrong with rips resoluition here. It should not be backtracking so far on `apache-beam`, and I had a previous case where it was going this with `snowflake-connector-python`. Pip does not need to backtrack so far back and is able to solve this requirement.

**Comment by notatallshaw** [comment]
I don't have a good understand on the interaction between resolvo and rip, but I would strongly suggest if somehow rip can guide resolve to try wheel based packages before sdist based packages, it will result in better performance overall.

**Comment by baszalmstra** [comment]
We have the option to first try all wheels before resorting to sdists for a specific package but now that I think about this it would be nice if we could also instruct resolvo to first backtrack further and only if that fails to also include sdists. 🤔

**Comment by notatallshaw** [comment]
It's something I've suggested for Pip (https://github.com/pypa/pip/issues/12035), and I now have an idea in my head how one would implement it for Pip. But I have other resolution improvements I am working on first over there, so I can't give you any real world data on if it helps or not.

**Comment by tdejager** [comment]
But its hard not to use them :)

**Comment by notatallshaw** [comment]
> But its hard not to use them :)

Well it's not that you avoid using them altogether. It's just that often when backtracking to older versions of a project and the next older version requires building an sdist instead of wheel it's likely that means the Python version your on is too new for that old of a package on that project.

It hence makes sense to try backtracking kna different projects, at least until you've exhausted all other equally likely backtracking opportunities.

At least that's my hypothesis.

**Comment by baszalmstra** [comment]
I think this can be done if we allow `DependencyProvider`s control over which requirement to decide on next. We can then first try requirement clauses for packages that would result in a wheel to be picked instead of one that would pick an sdist.

**Comment by aochagavia** [comment]
I have a hunch that this problem might be caused by a bug in resolvo. I think [this line](https://github.com/mamba-org/resolvo/blob/d39c732d8221eae6400669425aead8afbaa9e774/src/solver/mod.rs#L230) should be a `continue` instead of a `return`. Not totally sure, though.

**Comment by baszalmstra** [comment]
That is indeed a bug! It means not all clauses for a solvable are added!

**Comment by tdejager** [comment]
Might be a bug, but had some discussion with @aochagavia offline, and changing it does not change the backtracking behavior. Makes sense because it only gets in the `Unknown` clause when its already at the `apache-beam-2.42.0.zip` version, then the extensive backtracking has already occured.

**Comment by tdejager** [comment]
> > But its hard not to use them :)
> 
> Well it's not that you avoid using them altogether. It's just that often when backtracking to older versions of a project and the next older version requires building an sdist instead of wheel it's likely that means the Python version you're on is too new for that old of a package on that project.
> 
> It hence makes sense to try backtracking on different projects, at least until you've exhausted all other equally likely backtracking opportunities.
> 
> At least that's my hypothesis.

I think that this idea.



> I think this can be done if we allow `DependencyProvider`s control over which requirement to decide on next. We can then first try requirement clauses for packages that would result in a wheel to be picked instead of one that would pick an sdist.

With this implementation still seems the way to go, I wonder what ripple effect such a change but I think we can only know by trying.

**Comment by notatallshaw** [comment]
> I wonder what ripple effect such a change but I think we can only know by trying.

Yeah, this is a very opinionated optimization I'm suggesting, and the specific details on the implementation are likely to make a big difference on resolving certain requirements.

I do think though the PyPI packing ecosystem does require opinionated optimizations to get "good" resolution behavior.
